FROM fedora:latest

RUN dnf update -y && dnf upgrade -y && dnf install gdb \ 
gcc which git gh alsa-lib-devel \
mesa-libGL-devel libX11-devel libXrandr-devel \
libXi-devel libXcursor-devel libXinerama-devel libatomic -y